spring:
 application:
  name: yu-ai-agent
 profiles:
   active: local
server:
  port: 8123

  ai:
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127


        stdio:
          servers-configuration: classpath:mcp-servers.json

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  # 需要替换为你自己的 key
  api-key: T6fnfDCikA1A2BYL5p175Moa

